version: '3.8'

services:
  postgres-server:
    image: postgres:latest
    container_name: cont-postgres-server
    environment:
      - POSTGRES_USER=adminUser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bddnode
    ports:
      - "5432:5432"
    networks:
      - net-postgres-server
    volumes:
      - data-postgres-volume:/var/lib/postgresql/data

networks:
  net-postgres-server:

volumes:
  data-postgres-volume: