export enum DomainExceptionCode {
	DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
	DRIVER_NAME_REQUIRED = 'DRIVER_NAME_REQUIRED',
	DRIVER_LASTNAME_REQUIRED = 'DRIVER_LASTNAME_REQUIRED',
	DRIVER_NID_INVALID = 'DRIVER_NID_INVALID',
	DRIVER_NOT_FOUND = 'DRIVER_NOT_FOUND',
}
