export enum DomainExceptionCode {
    DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
    VEHICLE_PLATE_REQUIRED = 'VEHICLE_PLATE_REQUIRED',
    VEHICLE_ORGANIZATION_REQUIRED = 'VEHICLE_ORGANIZATION_REQUIRED',
    VEHICLE_NID_INVALID = 'VEHICLE_NID_INVALID',
    VEHICLE_NOT_FOUND = 'VEHICLE_NOT_FOUND'
}