export enum DomainExceptionCode {
	DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
	USER_USERNAME_REQUIRED = 'USER_USERNAME_REQUIRED',
	USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
	USER_EMAIL_INVALID = 'USER_EMAIL_INVALID',
	USER_PASSWORD_REQUIRED = 'USER_PASSWORD_REQUIRED',
	USER_PASSWORD_LENGTH_INVALID = 'USER_PASSWORD_LENGTH_INVALID',
	USER_SUBJECT_INVALID = 'USER_SUBJECT_INVALID',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
 }