export enum DomainExceptionCode {
	DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
	ROUTE_START_AT_REQUIRED = 'ROUTE_START_AT_REQUIRED',
	ROUTE_ENDS_AT_REQUIRED = 'ROUTE_ENDS_AT_REQUIRED',
	ROUTE_TRAVEL_TIME_REQUIRED = 'ROUTE_TRAVEL_TIME_REQUIRED',
	ROUTE_TOTAL_STOPS_REQUIRED = 'ROUTE_TOTAL_STOPS_REQUIRED',
	ROUTE_ACTION_REQUIRED = 'ROUTE_ACTION_REQUIRED',
	ROUTE_ORGANIZATION_ID_REQUIRED = 'ROUTE_ORGANIZATION_ID_REQUIRED',
	ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
	ROUTE_DRIVER_CONFLICT = 'ROUTE_DRIVER_CONFLICT',
	ROUTE_VEHICLE_CONFLICT = 'ROUTE_VEHICLE_CONFLICT',
}
