export enum DomainExceptionCode {
	DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
	ORGANIZATION_NAME_REQUIRED = 'ORGANIZATION_NAME_REQUIRED',
	ORGANIZATION_NID_INVALID = 'ORGANIZATION_NID_INVALID',
	ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
}
